# Generated by Django 5.0.7 on 2025-03-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_article_alter_blog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Trending', 'Trending'), ('Popular', 'Popular')], max_length=100),
        ),
    ]
