# Generated by Django 5.0.7 on 2025-03-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Popular', 'Popular'), ('Trending', 'Trending')], max_length=100),
        ),
    ]
