# Generated by Django 5.0.7 on 2025-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_noticia_alter_blog_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending')], max_length=100),
        ),
    ]
