# Generated by Django 5.0.7 on 2025-03-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_noticia_link_alter_blog_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='biografias/')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
