# Generated by Django 5.0.7 on 2025-03-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_blog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending')], max_length=100),
        ),
    ]
